<?php

namespace common\models;

use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "file_kp".
 *
 * @property int $id_file_kp
 * @property int|null $id_proekt
 * @property string|null $file_kp_content
 * @property string|null $file_kp_name
 * @property int|null $file_kp_kz
 * @property string|null $file_kp_ds
 * @property string|null $file_kp_del
 *
 * @property Proekt $proekt
 */
class FileKp extends \yii\db\ActiveRecord
{
    public $file;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'file_kp';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id_proekt', 'file_kp_kz'], 'integer'],
            [['file_kp_content'], 'string'],
            [['file_kp_ds'], 'safe'],
            [['file_kp_name'], 'string', 'max' => 250],
            [['file_kp_del'], 'string', 'max' => 1],
            [['id_proekt'], 'exist', 'skipOnError' => true, 'targetClass' => Proekt::className(), 'targetAttribute' => ['id_proekt' => 'id_proekt']],
            [['file'], 'file', 'maxFiles'=>10],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id_file_kp' => 'Id Файла',
            'id_proekt' => 'Id Проекта',
            'file_kp_content' => 'КП Содержимое',
            'file_kp_name' => 'КП Имя',
            'file_kp_kz' => 'КП кто залил',
            'file_kp_ds' => 'КП дата создания',
            'file_kp_del' => 'КП удален',
            'file' => 'Файл',
        ];
    }

    /**
     * Gets query for [[Proekt]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getProekt()
    {
        return $this->hasOne(Proekt::className(), ['id_proekt' => 'id_proekt']);
    }
    public function beforeSave($insert)
    {
////        if ($file = UploadedFile::getInstances($this, 'file')){
////            $dir = Yii::getAlias('@images').'/kp/';
////            foreach ($file as $f){
////                $this->file_kp_name = $f->baseName.'.'.$f->extension;
////
////                $this->file_kp_content = strtotime('now').'_'.Yii::$app->getSecurity()->generateRandomString(6).'.'.$f->extension;
////                $f->saveAs($dir.$this->file_kp_content);
////
////            }
////
////
////        }
//        if ($file = UploadedFile::getInstance($this, 'file')){
//            $dir = Yii::getAlias('@images').'/kp/';
//            $this->file_kp_name = $file->baseName.'.'.$file->extension;
//
//            $this->file_kp_content = strtotime('now').'_'.Yii::$app->getSecurity()->generateRandomString(6).'.'.$file->extension;
//            $file->saveAs($dir.$this->file_kp_content);
//
//
//        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
